spring:
  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  devtools:
    add-properties: false

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop

  mvc:
    throw-exception-if-no-handler-found: true

springdoc.swagger-ui.path: /swagger-ui.html

app:
  secret-key: VGhleSB3YW5kZXJlZCBpbnRvIGEgc3RyYW5nZSBUaWtpIGJhciBvbiB0aGUgZWRnZSBvZiB0aGUgc21hbGwgYmVhY2ggdG93bi4=