spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop

  mvc:
    throw-exception-if-no-handler-found: true

springdoc.swagger-ui.path: /swagger-ui.html