spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop

  mvc:
    throw-exception-if-no-handler-found: true

# swagger-ui custom path
springdoc.swagger-ui.path: /swagger-ui.html